version: 1.1.{build}
os: Visual Studio 2019
skip_tags: true
configuration: Release

install:
  - cmd: git submodule update --init --recursive

before_build:
  - cmd: dotnet --info
  - cmd: dotnet restore --verbosity n

build_script:
  - cmd: dotnet build -c Release ExifLibrary\